### ISSUE TITLE
when nats down hemera fails with this.write error

### ISSUE THREAD

**Issue by veeramarni** [hemerajs/hemera#164]
## Description
When you use plugin and start the server with NATS down then you will see following error. 

## Actual Result

/usr/src/app/node_modules/pino/lib/tools.js:102
    this.write(m, o, z)
         ^

TypeError: this.write is not a function
    at Client.LOG (/usr/src/app/node_modules/pino/lib/tools.js:102:10)
    at emitOne (events.js:115:13)
    at Client.emit (events.js:210:7)
    at Socket.<anonymous> (/usr/src/app/node_modules/nats/lib/nats.js:454:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

## Context

- [x] nats-hemera (core)

## Your Environment
- NATS: X.X.X
- Hemera: latest
- NodeJs: 8.4.0
- Environment name and version: MacOS and docker
- Operating System and version:

**Comment by StarpTech** [comment]
Hi, could you provide an example? Thanks.

**Comment by veeramarni** [comment]
Here is the example plugin.
```
'use strict';

const Hp = require('hemera-plugin');

exports.plugin = Hp(function hemeraTestPlugin(hemera, options, next) {
    const topic = 'testPlugin';
    hemera.log.info('received options (%j)', options);
    hemera.add({
        topic,
        cmd: 'add',
    }, async function (req) {
        const result = await Promise.resolve({
            result: req.a + req.b,
        });
        return result;
    });

    next();
});

exports.options = {
    name: 'example-plugin',
};

exports.attributes = {
    pkg: require('../../package.json'),
};

```

**Comment by veeramarni** [comment]
And try with server

```
const client = nats.connect({
    'url': process.env.NATS_URL,
    'user': process.env.NATS_USER,
    'pass': process.env.NATS_PW,
});


const logLevel = process.env.HEMERA_LOG_LEVEL as Hemera.LogLevel || 'info';
// make sure not to use ES6 shortcuts for same object

const hemera = new Hemera(client, {
    logLevel: logLevel,
    childLogger: true,
    tag: 'hemera-server',
    timeout: 10000,
});

hemera.use(HemeraJoi);

hemera.use(ExampleHemera, {
   
});

// hemera.setOption('payloadValidator', 'hemera-joi');

hemera.ready(() => {
    // let Joi = hemera.exposition['hemera-joi'].joi;

});

```

**Comment by StarpTech** [comment]
I don't understand. What you expect?

**Comment by veeramarni** [comment]
Just updated the `pino` error we get. Shouldn't we get an exception about NATS not available instead of `TypeError: this.write is not a function`

**Comment by StarpTech** [comment]
Which version are you using? The plugin is invalid for Hemera 2

**Comment by StarpTech** [comment]
This is correct

```js
'use strict';

const Hp = require('hemera-plugin');

exports.plugin = Hp(function hemeraTestPlugin(hemera, options, next) {
    const topic = 'testPlugin';
    hemera.log.info('received options (%j)', options);
    hemera.add({
        topic,
        cmd: 'add',
    }, async function (req) {
        const result = await Promise.resolve({
            result: req.a + req.b,
        });
        return result;
    });

    next();
});

exports.options = {
    name: 'example-plugin',
};
```

What is this ?

```js
const logLevel = process.env.HEMERA_LOG_LEVEL as Hemera.LogLevel || 'info';
// make sure not to use ES6 shortcuts for same object
```

**Comment by StarpTech** [comment]
What's the status?

**Comment by StarpTech** [comment]
Close this issue because inactivity. Feel free to reopen.

**Comment by StarpTech** [comment]
I can't reproduce I get the correct error message

```js
'use strict'

const Hemera = require('nats-hemera')
const nats = require('nats').connect()
const Hp = require('hemera-plugin')

const myPlugin = Hp(
  function myPlugin(hemera, options, done) {
    hemera.add(
      {
        topic: 'math',
        cmd: 'add'
      },
      (resp, cb) => {
        cb(null, resp.a + resp.b)
      }
    )

    done()
  })

const hemera = new Hemera(nats, {
  logLevel: 'error',
  childLogger: true,
  tag: 'hemera-server',
  timeout: 10000,
})

hemera.use(myPlugin, {

})

hemera.ready((err) => {
  console.error(err)
})
```

**Comment by StarpTech** [comment]
@veeramarni please provide further information.

**Comment by StarpTech** [comment]
Close this issue because of inactivity. Feel free to reopen.
