### ISSUE TITLE
hemera-web have some errors.

### ISSUE THREAD

**Issue by arden** [hemerajs/hemera#85]
when i'm run: node web.js in examples.

[2017-05-12T06:43:49.141Z] ERROR (hemera-f09583d25d6f5b4d/21188 on yaochen): No topic to request
    HemeraError
        at Hemera.act (G:\source\node\微服务\hemera\packages\hemera\lib\index.js:893:19)
        at _server.Micro (G:\source\node\微服务\hemera\packages\hemera-web\lib\index.js:71:27)
        at resolve (G:\source\node\微服务\hemera\packages\hemera-web\node_modules\micro\lib\server.js:24:34)
        at Promise._execute (G:\source\node\微服务\hemera\packages\hemera-web\node_modules\bluebird\js\release\debuggability.js:300:9)
        at Promise._resolveFromExecutor (G:\source\node\微服务\hemera\packages\hemera-web\node_modules\bluebird\js\release\promise.js:483:18)
        at new Promise (G:\source\node\微服务\hemera\packages\hemera-web\node_modules\bluebird\js\release\promise.js:79:10)
        at Function.exports.run (G:\source\node\微服务\hemera\packages\hemera-web\node_modules\micro\lib\server.js:24:3)
        at Server.server (G:\source\node\微服务\hemera\packages\hemera-web\node_modules\micro\lib\server.js:13:50)
        at emitTwo (events.js:106:13)
        at Server.emit (events.js:194:7)
        at parserOnIncoming (_http_server.js:563:12)
        at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
HemeraError
    at Hemera.act (G:\source\node\微服务\hemera\packages\hemera\lib\index.js:893:19)
    at _server.Micro (G:\source\node\微服务\hemera\packages\hemera-web\lib\index.js:71:27)
    at resolve (G:\source\node\微服务\hemera\packages\hemera-web\node_modules\micro\lib\server.js:24:34)
    at Promise._execute (G:\source\node\微服务\hemera\packages\hemera-web\node_modules\bluebird\js\release\debuggability.js:300:9)
    at Promise._resolveFromExecutor (G:\source\node\微服务\hemera\packages\hemera-web\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (G:\source\node\微服务\hemera\packages\hemera-web\node_modules\bluebird\js\release\promise.js:79:10)
    at Function.exports.run (G:\source\node\微服务\hemera\packages\hemera-web\node_modules\micro\lib\server.js:24:3)
    at Server.server (G:\source\node\微服务\hemera\packages\hemera-web\node_modules\micro\lib\server.js:13:50)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:194:7)
    at parserOnIncoming (_http_server.js:563:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)

but the browser can response ok.

**Comment by StarpTech** [comment]
@arden the error is clear `No topic to request` you always have to pass a topic as query or payload.

I get this:
```
node .\examples\web.js
[2017-05-12T07:32:01.115Z] INFO (hemera-9c80a0a538c44c7ca31239c505eb42cc/10456 on starptech): hemera-web PLUGIN - ADDED!
[2017-05-12T07:32:01.123Z] INFO (hemera-9c80a0a538c44c7ca31239c505eb42cc/10456 on starptech): Connected!
[2017-05-12T07:32:01.124Z] INFO (hemera-9c80a0a538c44c7ca31239c505eb42cc/10456 on starptech): HTTP Server listening on: localhost:3000
[2017-05-12T07:32:01.130Z] INFO (hemera-9c80a0a538c44c7ca31239c505eb42cc/10456 on starptech): ADD - ADDED
    topic: "math"
    cmd: "add"
[2017-05-12T07:32:01.131Z] INFO (hemera-9c80a0a538c44c7ca31239c505eb42cc/10456 on starptech): ADD - ADDED
    topic: "math"
    cmd: "sub"
```

**Comment by StarpTech** [comment]
@arden please reopen if you have still the problem.
